
TRADE_ALLOWED = 0
TRADE_REACH_MAX_INCREASE_BUY = 1
TRADE_REACH_MAX_DECREASE_BUY = 2
TRADE_REACH_MAX_INCREASE_BEARISHBUY = 3
TRADE_REACH_MAX_DECREASE_BEARISHBUY = 4
TRADE_NO_BEARISHBUY = 5
TRADE_REACH_MAX_INCREASE_SELL = 6
TRADE_REACH_MAX_DECREASE_SELl = 7
TRADE_REACH_MAX_INCREASE_BEARISHSELL = 8
TRADE_REACH_MAX_DECREASE_BEARISHSELL = 9
TRADE_NO_BEARISHSELL = 10